################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/Justin\ Stadlbauer/Documents/Spring\ 2018/IoT/Cube\ -\ IOT\ -\ AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/vl53l0x/vl53l0x_api.c \
C:/Users/Justin\ Stadlbauer/Documents/Spring\ 2018/IoT/Cube\ -\ IOT\ -\ AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/vl53l0x/vl53l0x_api_calibration.c \
C:/Users/Justin\ Stadlbauer/Documents/Spring\ 2018/IoT/Cube\ -\ IOT\ -\ AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/vl53l0x/vl53l0x_api_core.c \
C:/Users/Justin\ Stadlbauer/Documents/Spring\ 2018/IoT/Cube\ -\ IOT\ -\ AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/vl53l0x/vl53l0x_api_ranging.c \
C:/Users/Justin\ Stadlbauer/Documents/Spring\ 2018/IoT/Cube\ -\ IOT\ -\ AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/vl53l0x/vl53l0x_api_strings.c \
C:/Users/Justin\ Stadlbauer/Documents/Spring\ 2018/IoT/Cube\ -\ IOT\ -\ AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/vl53l0x/vl53l0x_platform_log.c 

OBJS += \
./Drivers/BSP/Components/vl53l0x/vl53l0x_api.o \
./Drivers/BSP/Components/vl53l0x/vl53l0x_api_calibration.o \
./Drivers/BSP/Components/vl53l0x/vl53l0x_api_core.o \
./Drivers/BSP/Components/vl53l0x/vl53l0x_api_ranging.o \
./Drivers/BSP/Components/vl53l0x/vl53l0x_api_strings.o \
./Drivers/BSP/Components/vl53l0x/vl53l0x_platform_log.o 

C_DEPS += \
./Drivers/BSP/Components/vl53l0x/vl53l0x_api.d \
./Drivers/BSP/Components/vl53l0x/vl53l0x_api_calibration.d \
./Drivers/BSP/Components/vl53l0x/vl53l0x_api_core.d \
./Drivers/BSP/Components/vl53l0x/vl53l0x_api_ranging.d \
./Drivers/BSP/Components/vl53l0x/vl53l0x_api_strings.d \
./Drivers/BSP/Components/vl53l0x/vl53l0x_platform_log.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/BSP/Components/vl53l0x/vl53l0x_api.o: C:/Users/Justin\ Stadlbauer/Documents/Spring\ 2018/IoT/Cube\ -\ IOT\ -\ AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/vl53l0x/vl53l0x_api.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L475xx -DUSE_HAL_DRIVER -DSENSOR '-DMBEDTLS_CONFIG_FILE=<aws_mbedtls_config.h>' -DENABLE_IOT_INFO -DENABLE_IOT_ERROR -DENABLE_IOT_WARNING -DUSE_MBED_TLS -DAWS -DUSE_WIFI -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Projects/B-L475E-IOT01/Applications/Cloud/AWS/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/CMSIS/Include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Projects/Common/AWS/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Projects/Common/Shared/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Middlewares/Third_Party/AWS/include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Middlewares/Third_Party/mbedTLS/include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/es_wifi" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/hts221" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/lis3mdl" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/lps22hb" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/vl53l0x"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/BSP/Components/vl53l0x/vl53l0x_api.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/Components/vl53l0x/vl53l0x_api_calibration.o: C:/Users/Justin\ Stadlbauer/Documents/Spring\ 2018/IoT/Cube\ -\ IOT\ -\ AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/vl53l0x/vl53l0x_api_calibration.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L475xx -DUSE_HAL_DRIVER -DSENSOR '-DMBEDTLS_CONFIG_FILE=<aws_mbedtls_config.h>' -DENABLE_IOT_INFO -DENABLE_IOT_ERROR -DENABLE_IOT_WARNING -DUSE_MBED_TLS -DAWS -DUSE_WIFI -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Projects/B-L475E-IOT01/Applications/Cloud/AWS/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/CMSIS/Include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Projects/Common/AWS/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Projects/Common/Shared/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Middlewares/Third_Party/AWS/include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Middlewares/Third_Party/mbedTLS/include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/es_wifi" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/hts221" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/lis3mdl" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/lps22hb" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/vl53l0x"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/BSP/Components/vl53l0x/vl53l0x_api_calibration.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/Components/vl53l0x/vl53l0x_api_core.o: C:/Users/Justin\ Stadlbauer/Documents/Spring\ 2018/IoT/Cube\ -\ IOT\ -\ AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/vl53l0x/vl53l0x_api_core.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L475xx -DUSE_HAL_DRIVER -DSENSOR '-DMBEDTLS_CONFIG_FILE=<aws_mbedtls_config.h>' -DENABLE_IOT_INFO -DENABLE_IOT_ERROR -DENABLE_IOT_WARNING -DUSE_MBED_TLS -DAWS -DUSE_WIFI -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Projects/B-L475E-IOT01/Applications/Cloud/AWS/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/CMSIS/Include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Projects/Common/AWS/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Projects/Common/Shared/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Middlewares/Third_Party/AWS/include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Middlewares/Third_Party/mbedTLS/include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/es_wifi" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/hts221" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/lis3mdl" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/lps22hb" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/vl53l0x"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/BSP/Components/vl53l0x/vl53l0x_api_core.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/Components/vl53l0x/vl53l0x_api_ranging.o: C:/Users/Justin\ Stadlbauer/Documents/Spring\ 2018/IoT/Cube\ -\ IOT\ -\ AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/vl53l0x/vl53l0x_api_ranging.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L475xx -DUSE_HAL_DRIVER -DSENSOR '-DMBEDTLS_CONFIG_FILE=<aws_mbedtls_config.h>' -DENABLE_IOT_INFO -DENABLE_IOT_ERROR -DENABLE_IOT_WARNING -DUSE_MBED_TLS -DAWS -DUSE_WIFI -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Projects/B-L475E-IOT01/Applications/Cloud/AWS/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/CMSIS/Include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Projects/Common/AWS/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Projects/Common/Shared/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Middlewares/Third_Party/AWS/include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Middlewares/Third_Party/mbedTLS/include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/es_wifi" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/hts221" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/lis3mdl" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/lps22hb" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/vl53l0x"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/BSP/Components/vl53l0x/vl53l0x_api_ranging.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/Components/vl53l0x/vl53l0x_api_strings.o: C:/Users/Justin\ Stadlbauer/Documents/Spring\ 2018/IoT/Cube\ -\ IOT\ -\ AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/vl53l0x/vl53l0x_api_strings.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L475xx -DUSE_HAL_DRIVER -DSENSOR '-DMBEDTLS_CONFIG_FILE=<aws_mbedtls_config.h>' -DENABLE_IOT_INFO -DENABLE_IOT_ERROR -DENABLE_IOT_WARNING -DUSE_MBED_TLS -DAWS -DUSE_WIFI -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Projects/B-L475E-IOT01/Applications/Cloud/AWS/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/CMSIS/Include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Projects/Common/AWS/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Projects/Common/Shared/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Middlewares/Third_Party/AWS/include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Middlewares/Third_Party/mbedTLS/include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/es_wifi" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/hts221" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/lis3mdl" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/lps22hb" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/vl53l0x"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/BSP/Components/vl53l0x/vl53l0x_api_strings.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/Components/vl53l0x/vl53l0x_platform_log.o: C:/Users/Justin\ Stadlbauer/Documents/Spring\ 2018/IoT/Cube\ -\ IOT\ -\ AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/vl53l0x/vl53l0x_platform_log.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -DSTM32L475xx -DUSE_HAL_DRIVER -DSENSOR '-DMBEDTLS_CONFIG_FILE=<aws_mbedtls_config.h>' -DENABLE_IOT_INFO -DENABLE_IOT_ERROR -DENABLE_IOT_WARNING -DUSE_MBED_TLS -DAWS -DUSE_WIFI -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Projects/B-L475E-IOT01/Applications/Cloud/AWS/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/CMSIS/Include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Projects/Common/AWS/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Projects/Common/Shared/Inc" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Middlewares/Third_Party/AWS/include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Middlewares/Third_Party/mbedTLS/include" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/es_wifi" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/hts221" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/lis3mdl" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/lps22hb" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/Justin Stadlbauer/Documents/Spring 2018/IoT/Cube - IOT - AWS/STM32CubeExpansion_Cloud_AWS_V1.1.0/Drivers/BSP/Components/vl53l0x"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/BSP/Components/vl53l0x/vl53l0x_platform_log.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


